name: minimal
start_date: 2020-01-01
end_date: 2020-08-17
nsimulations: 10
dt: 0.25

spatial_setup:
  census_year: 2010
  base_path: data
  modeled_states:
   - NY
  setup_name: minimal
  geodata: geodata.csv
  mobility: mobility.csv
  popnodes: pop2010
  nodenames: geoid
  include_in_report: include_in_report

seeding:
  method: FolderDraw
  lambda_file: data/minimal/seeding.csv
  folder_path: importation/minimal/
  seeding_file_type: seed
  perturbation_sd: 3

seir:
  parameters:
    alpha: 0.99
    sigma: 1 / 5.2
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1 / 2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3

interventions:
  scenarios:
    - Scenario1
  settings:
    local_variation:
      template: ReduceR0
      value:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    NEWYORK_lockdown_partial:
      template: ReduceR0
      period_start_date: 2020-03-22
      period_end_date: 2020-05-28
      value:
        distribution: truncnorm
        mean: 0.6
        sd: 0.3
        a: 0
        b: 0.9
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .05
        a: -1
        b: 1
    NEWYORK_postlockdown_partial:
      template: ReduceR0
      period_start_date: 2020-05-29
      period_end_date: 2020-08-17
      value:
        distribution: truncnorm
        mean: 0.48
        sd: 0.3
        a: 0.2
        b: 0.84
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .05
        a: -1
        b: 1
    Scenario1:
      template: Stacked
      scenarios: ["local_variation", "NEWYORK_lockdown_partial", "NEWYORK_postlockdown_partial"]
    Scenario2:
      template: Stacked
      scenarios: ["local_variation", "NEWYORK_lockdown_partial"]


outcomes:
  method: delayframe
  param_from_file: TRUE
  # param_place_file: ../../Outcomes/data/usa-geoid-params-output.parquet
  param_place_file: "hospitalization.small.hpar.parquet"
  scenarios:
    - low
  settings:
    low:
      incidH:
        source: incidI
        probability:
          value:
            distribution: fixed
            value: .0175
        delay:
          value:
            distribution: fixed
            value: 7
        duration:
          value:
            distribution: fixed
            value: 7
          name: hosp_curr
      incidD:
        source: incidI
        probability:
          value:
            distribution: fixed
            value: .0025
        delay:
          value:
            distribution: fixed
            value: 20
      incidICU:
        source: incidH
        probability: 
          value:
            distribution: fixed
            value: 0.167
        delay:
          value:
            distribution: fixed
            value: 3
        duration:
          value:
            distribution: fixed
            value: 8
          name: icu_curr
      incidVent:
        source: incidICU
        probability: 
          value:
            distribution: fixed
            value: 0.463
        delay:
          value:
            distribution: fixed
            value: 1
        duration:
          value:
            distribution: fixed
            value: 7
          name: vent_curr
      incidC:
        source: incidI
        probability:
          value:
            distribution: truncnorm
            mean: .1
            sd: .1
            a: 0
            b: 1
          perturbation:
            distribution: truncnorm
            mean: 0
            sd: .1
            a: -1
            b: 1
        delay:
          value:
            distribution: fixed
            value: 7

filtering:
  simulations_per_slot: 10
  do_filtering: TRUE
  data_path: data/us_data.csv
  likelihood_directory: importation/likelihood/
  statistics:
    sum_deaths:
      name: sum_deaths
      aggregator: sum
      period: "1 weeks"
      sim_var: incidD
      data_var: death_incid
      remove_na: TRUE
      add_one: FALSE
      likelihood:
        dist: sqrtnorm
        param: [.1]
    sum_confirmed:
      name: sum_confirmed
      aggregator: sum
      period: "1 weeks"
      sim_var: incidC
      data_var: confirmed_incid
      remove_na: TRUE
      add_one: FALSE
      likelihood:
        dist: sqrtnorm
        param: [.2]
  hierarchical_stats_geo:
    local_var_hierarchy:
      name: local_variance
      module: seir
      geo_group_col: USPS
      transform: none
    local_conf:
      name: probability_incidI_incidC
      module: hospitalization
      geo_group_col: USPS
      transform: logit
  priors:
    local_var_prior:
      name: local_variation
      module: seir
      likelihood:
        dist: normal
        param:
        - 0
        - 1
  
