## This config file will not generate a makefile as currently configured.
## We want to show all of the options available, even though some are not appropriately general for this scope
## In particular, importation and the associated FolderDraw seeding method only work for sets of US states.
## The comments in this file explain how to modify it based on your use case
## Items that must be changed for the process to work are designated by < >.
## Some items in the config can be removed, and we have tried to note these with comments as well.

name: minimal
start_date: 2020-01-01
end_date: 2020-05-09
nsimulations: 100
dt: 0.25
## dynfilter_path: data/filter.txt ## this method of filtering is not currently working

spatial_setup:
  census_year: 2010
  base_path: data
  modeled_states: # To model a region that is not a state, remove modeled_states and the importation: block
   - NY # e.g., MD  You can provide as many of these as you like, but more counties means slower runs
  setup_name: minimal
  geodata: geodata.csv
  mobility: mobility.csv
  popnodes: pop2010
  nodenames: geoid
  include_in_report: include_in_report

seeding: ## If removing the importation, comment out this seeding block
  method: FolderDraw
  # method: PoissonDistributed
  folder_path: importation/minimal/
  lambda_file: data/minimal/seeding.csv
  perturbation_sd: 3

seir:
  parameters:
    alpha: .99
    sigma: 1 / 5.2
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1/2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3.5

interventions:
  scenarios:
    - Scenario1
    # - Scenario2
  settings:
    local_variation:
      template: ReduceR0
      value:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: 0.1
        a: -1
        b: 1
    UK:
      template: ReduceR0
      period_start_date: 2020-03-25
      value:
        distribution: truncnorm
        mean: 0.6
        sd: .1
        a: 0
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: 0.1
        a: -1
        b: 1
    Influenza1918:
      template: ReduceR0
      period_start_date: 2020-03-25
      value:
        distribution: uniform
        low: .40
        high: .60
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: 0.1
        a: -1
        b: 1
    Scenario1:
      template: Stacked
      scenarios: ["local_variation","UK"]
    Scenario2:
      template: Stacked
      scenarios: ["local_variation","Influenza1918"]

hospitalization:
  paths:
    output_path: hospitalization
    run_age_adjust: TRUE
  parameters:
    time_hosp: [log(7), 0.3]
    time_disch: [log(7), log(1.22)]
    time_ICU: [log(3), 0.3]
    time_ICUdur: [log(8), 0.2]
    time_ventdur: [log(7), 0.2]
    time_vent: [log(1), 0.4]
    p_death: [.005]
    p_death_names: ["med"]
    p_hosp_inf: [0.05]
    time_onset_death: [2.63, 0.72]

filtering:
  simulations_per_slot: 100
  do_filtering: TRUE
  data_path: data/us_data.csv
  likelihood_directory: importation/likelihood/
  statistics:
    sum_deaths:
      name: sum_deaths
      aggregator: sum
      period: "1 weeks"
      sim_var: incidD
      data_var: death_incid
      remove_na: TRUE
      add_one: FALSE
      likelihood:
        dist: sqrtnorm
        param: [.1]
    sum_hosp:
      name: sum_hosp
      aggregator: sum
      period: "1 days"
      sim_var: incidH
      data_var : conf_incid
      remove_na: TRUE
      add_one: FALSE
      likelihood:
        dist: sqrtnorm
        param: [.5]


## Report generation is still in it's infancy.
## The parameters in this block are only used in our draft state_report rmarkdown template 
## This section can be removed if you are not using that template.
## Many of the parameters in this section may be broken, as that report has been under a lot of development recently.
report:
  data_settings:
    pop_year: 2010
  plot_settings:
    plot_intervention: TRUE
  formatting:
    scenario_labels_short: []
    scenario_labels:
    - Worst Case Uncontrolled Spread
    - Another Scenario
    scenario_colors: ["#D95F02", "#1B9E77"]
    pdeath_labels: ["0.25% IFR", "0.5% IFR", "1% IFR"]
    display_dates: ["2020-05-01", "2020-07-01", "2020-09-01"]
