name: USA
start_date: 2020-01-01
end_date: 2020-12-19
nsimulations: 300
dt: 0.25

spatial_setup:
  census_year: 2019
  base_path: data
  modeled_states: 
   - AZ
  setup_name: usa_inference_territories
  geodata: geodata_az_2019.csv
  mobility: mobility_az_2011-2015.csv
  popnodes: pop2019est
  nodenames: geoid
  include_in_report: include_in_report

seeding:
  method: FolderDraw
  seeding_file_type: seed
  folder_path: importation/minimal/
  lambda_file: data/minimal/seeding_az.csv
  perturbation_sd: 3

seir:
  parameters:
    alpha: 0.99
    sigma: 1 / 5.2
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1 / 2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3

interventions:
  scenarios:
    - inference
  settings:
    local_variance:
      template: ReduceR0
      value:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_jan:
      template: ReduceR0
      period_start_date: 2020-01-01
      period_end_date: 2020-01-31
      value:
        distribution: truncnorm
        mean: -0.2
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_feb:
      template: ReduceR0
      period_start_date: 2020-02-01
      period_end_date: 2020-02-29
      value:
        distribution: truncnorm
        mean: -0.133
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_mar:
      template: ReduceR0
      period_start_date: 2020-03-01
      period_end_date: 2020-03-31
      value:
        distribution: truncnorm
        mean: -0.067
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_may:
      template: ReduceR0
      period_start_date: 2020-05-01
      period_end_date: 2020-05-31
      value:
        distribution: truncnorm
        mean: 0.067
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_jun:
      template: ReduceR0
      period_start_date: 2020-06-01
      period_end_date: 2020-06-30
      value:
        distribution: truncnorm
        mean: 0.133
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_jul:
      template: ReduceR0
      period_start_date: 2020-07-01
      period_end_date: 2020-07-31
      value:
        distribution: truncnorm
        mean: 0.2
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_aug:
      template: ReduceR0
      period_start_date: 2020-08-01
      period_end_date: 2020-08-31
      value:
        distribution: truncnorm
        mean: 0.133
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_sep:
      template: ReduceR0
      period_start_date: 2020-09-01
      period_end_date: 2020-09-30
      value:
        distribution: truncnorm
        mean: 0.067
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_oct:
      template: ReduceR0
      period_start_date: 2020-10-01
      period_end_date: 2020-10-31
      value:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_nov:
      template: ReduceR0
      period_start_date: 2020-11-01
      period_end_date: 2020-11-30
      value:
        distribution: truncnorm
        mean: -0.067
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    seas_dec:
      template: ReduceR0
      period_start_date: 2020-12-01
      period_end_date: 2020-11-31
      value:
        distribution: truncnorm
        mean: -0.133
        sd: .1
        a: -1
        b: 1
    ARIZONA_lockdown_partial:
      template: ReduceR0
      affected_geoids: ["04011", "04012", "04009", "04023", "04007", "04001", "04017", "04003", "04005", "04027", "04015", "04025", "04021", "04019", "04013"]
      period_start_date: 2020-03-31
      period_end_date: 2020-05-15
      value:
        distribution: truncnorm
        mean: 0.6
        sd: 0.3
        a: 0
        b: 0.9
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .05
        a: -1
        b: 1
    ARIZONA_open_p1_partial:
      template: ReduceR0
      affected_geoids: ["04011", "04012", "04009", "04023", "04007", "04001", "04017", "04003", "04005", "04027", "04015", "04025", "04021", "04019", "04013"]
      period_start_date: 2020-05-16
      period_end_date: 2020-06-28
      value:
        distribution: truncnorm
        mean: 0.6
        sd: 0.3
        a: 0
        b: 0.9
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .05
        a: -1
        b: 1
    ARIZONA_close1_partial:
      template: ReduceR0
      affected_geoids: ["04011", "04012", "04009", "04023", "04007", "04001", "04017", "04003", "04005", "04027", "04015", "04025", "04021", "04019", "04013"]
      period_start_date: 2020-06-29
      period_end_date: 2020-10-01
      value:
        distribution: truncnorm
        mean: 0.6
        sd: 0.3
        a: 0
        b: 0.9
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .05
        a: -1
        b: 1
    ARIZONA_open_p2_partial:
      template: ReduceR0
      affected_geoids: ["04011", "04012", "04009", "04023", "04007", "04001", "04017", "04003", "04005", "04027", "04015", "04025", "04021", "04019", "04013"]
      period_start_date: 2020-10-02
      period_end_date: 2020-12-19
      value:
        distribution: truncnorm
        mean: 0.6
        sd: 0.3
        a: 0
        b: 0.9
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .05
        a: -1
        b: 1
    state_scenarios:
      template: Stacked
      scenarios: ["ARIZONA_lockdown_partial", "ARIZONA_open_p1_partial", "ARIZONA_close1_partial", "ARIZONA_open_p2_partial"]
    months:
      template: Stacked
      scenarios: ["seas_jan", "seas_feb", "seas_mar", "seas_may", "seas_jun", "seas_jul", "seas_aug", "seas_sep", "seas_oct", "seas_nov", "seas_dec"]
    inference:
      template: Stacked
      scenarios: ["local_variance", "state_scenarios", "months"]
    
outcomes:
  method: delayframe
  param_from_file: TRUE
  param_place_file: "usa-geoid-params-output.parquet"
  scenarios:
    - low
  settings:
    low:
      incidH:
        source: incidI
        probability:
          value:
            distribution: fixed
            value: .0175
        delay:
          value:
            distribution: fixed
            value: 7
        duration:
          value:
            distribution: fixed
            value: 7
          name: hosp_curr
      incidD:
        source: incidI
        probability:
          value:
            distribution: fixed
            value: .0025
        delay:
          value:
            distribution: fixed
            value: 20
      incidICU:
        source: incidH
        probability: 
          value:
            distribution: fixed
            value: 0.167
        delay:
          value:
            distribution: fixed
            value: 3
        duration:
          value:
            distribution: fixed
            value: 8
          name: icu_curr
      incidVent:
        source: incidICU
        probability: 
          value:
            distribution: fixed
            value: 0.463
        delay:
          value:
            distribution: fixed
            value: 1
        duration:
          value:
            distribution: fixed
            value: 7
          name: vent_curr
      incidC:
        source: incidI
        probability:
          value:
            distribution: truncnorm
            mean: .1
            sd: .1
            a: 0
            b: 1
          perturbation:
            distribution: truncnorm
            mean: 0
            sd: .05
            a: -1
            b: 1
        delay:
          value:
            distribution: fixed
            value: 7

filtering:
  simulations_per_slot: 250
  do_filtering: TRUE
  data_path: data/az_data.csv
  likelihood_directory: importation/likelihood/
  statistics:
    sum_deaths:
      name: sum_deaths
      aggregator: sum
      period: "1 weeks"
      sim_var: incidD
      data_var: death_incid
      remove_na: FALSE
      add_one: FALSE
      likelihood:
        dist: sqrtnorm
        param: [.4]
    sum_confirmed:
      name: sum_confirmed
      aggregator: sum
      period: "1 weeks"
      sim_var: incidC
      data_var: confirmed_incid
      remove_na: FALSE
      add_one: TRUE
      likelihood:
        dist: pois
  hierarchical_stats_geo:
    local_var_hierarchy:
      name: local_variance
      module: seir
      geo_group_col: USPS
      transform: none
    local_conf:
      name: probability_incidI_incidC
      module: hospitalization
      geo_group_col: USPS
      transform: logit
  priors:
    local_var_prior:
      name: local_variance
      module: seir
      likelihood:
        dist: normal
        param:
        - 0
        - 1
    seas_jan_prior:
      name: seas_jan
      module: seir
      likelihood:
        dist: normal
        param:
        - -0.2
        - 1
    seas_feb_prior:
      name: seas_feb
      module: seir
      likelihood:
        dist: normal
        param:
        - -0.133
        - 1
    seas_mar_prior:
      name: seas_mar
      module: seir
      likelihood:
        dist: normal
        param:
        - -0.067
        - 1
    seas_may_prior:
      name: seas_may
      module: seir
      likelihood:
        dist: normal
        param:
        - 0.067
        - 1
    seas_jun_prior:
      name: seas_jun
      module: seir
      likelihood:
        dist: normal
        param:
        - 0.133
        - 1
    seas_jul_prior:
      name: seas_jul
      module: seir
      likelihood:
        dist: normal
        param:
        - 0.2
        - 1
    seas_aug_prior:
      name: seas_aug
      module: seir
      likelihood:
        dist: normal
        param:
        - 0.133
        - 1
    seas_sep_prior:
      name: seas_sep
      module: seir
      likelihood:
        dist: normal
        param:
        - 0.067
        - 1
    seas_oct_prior:
      name: seas_oct
      module: seir
      likelihood:
        dist: normal
        param:
        - 0
        - 1
    seas_nov_prior:
      name: seas_nov
      module: seir
      likelihood:
        dist: normal
        param:
        - -0.067
        - 1
