name: USA-NY
start_date: 2020-01-31
end_date: 2020-06-30
nsimulations: 1000
dt: 0.25

spatial_setup:
  census_year: 2010
  base_path: data
  modeled_states: # To model a region that is not a state, remove modeled_states and the importation: block
   - NY # e.g., MD  You can provide as many of these as you like, but more counties means slower runs
  setup_name: minimal
  geodata: geodata.csv
  mobility: mobility.csv
  popnodes: pop2010
  nodenames: geoid
  include_in_report: include_in_report

seeding:
  method: FolderDraw
  # method: PoissonDistributed
  folder_path: importation/minimal/
  lambda_file: data/minimal/seeding.csv
  perturbation_sd: 3

seir:
  parameters:
    alpha: 0.99
    sigma: 1 / 5.2
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1/2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3.5

interventions:
  scenarios:
    - local_variance_LockdownWideEffect_post50_firstcase_10x
  settings:
    local_variance:
      template: ReduceR0
      value:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    NEWYORK_lockdown_partial:
      template: ReduceR0
      affected_geoids: ["36001", "36003", "36005", "36007", "36009", "36011", "36013", "36015", "36017", "36019", "36021", "36023", "36025", "36027", "36029", "36031", "36033", "36035", "36037", "36039", "36041", "36043", "36045", "36047", "36049", "36051", "36053", "36055", "36057", "36059", "36061", "36063", "36065", "36067", "36069", "36071", "36073", "36075", "36077", "36079", "36081", "36083", "36085", "36087", "36089", "36091", "36093", "36095", "36097", "36099", "36101", "36103", "36105", "36107", "36109", "36111", "36113", "36115", "36117", "36119", "36121", "36123"]
      period_start_date: 2020-03-22
      period_end_date: 2020-05-16
      value:
        distribution: truncnorm
        mean: 0.6
        sd: 0.3
        a: 0.2
        b: 0.9
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: .1
        a: -1
        b: 1
    NEWYORK_postlockdown_partial:
      template: ReduceR0
      affected_geoids: ["36001", "36003", "36005", "36007", "36009", "36011", "36013", "36015", "36017", "36019", "36021", "36023", "36025", "36027", "36029", "36031", "36033", "36035", "36037", "36039", "36041", "36043", "36045", "36047", "36049", "36051", "36053", "36055", "36057", "36059", "36061", "36063", "36065", "36067", "36069", "36071", "36073", "36075", "36077", "36079", "36081", "36083", "36085", "36087", "36089", "36091", "36093", "36095", "36097", "36099", "36101", "36103", "36105", "36107", "36109", "36111", "36113", "36115", "36117", "36119", "36121", "36123"]
      period_start_date: 2020-05-17
      period_end_date: 2020-06-30
      value:
        distribution: uniform
        low: 0.1
        high: 0.45
    LockdownWideEffect_post50_firstcase_10x:
      template: Stacked
      scenarios: ["NEWYORK_lockdown_partial", "NEWYORK_postlockdown_partial"]
    local_variance_LockdownWideEffect_post50_firstcase_10x:
      template: Stacked
      scenarios: ["local_variance", "LockdownWideEffect_post50_firstcase_10x"]

hospitalization:
  paths:
    output_path: hospitalization
    run_age_adjust: TRUE
  parameters:
    time_hosp: [log(7), 0.3]
    time_disch: [log(7), log(1.22)]
    time_ICU: [log(3), 0.3]
    time_ICUdur: [log(8), 0.2]
    time_ventdur: [log(7), 0.2]
    time_vent: [log(1), 0.4]
    p_death: [.0025]
    p_death_names: ["low"]
    p_hosp_inf: [0.025]
    time_onset_death: [2.63, 0.72]

filtering:
  simulations_per_slot: 250
  do_filtering: TRUE
  data_path: data/us_data.csv
  likelihood_directory: importation/likelihood/
  statistics:
    sum_deaths:
      name: sum_deaths
      aggregator: sum
      period: "1 weeks"
      sim_var: incidD
      data_var: death_incid
      remove_na: TRUE
      add_one: FALSE
      likelihood:
        dist: sqrtnorm
        param: [.1]
    sum_hosp:
      name: sum_hosp
      aggregator: sum
      period: "1 days"
      sim_var: incidH
      data_var : conf_incid
      remove_na: TRUE
      add_one: FALSE
      likelihood:
        dist: sqrtnorm
        param: [.5]

report:
  data_settings:
    pop_year: 2010
  plot_settings:
    plot_intervention: TRUE
  formatting:
    scenario_labels_short: []
    scenario_labels:
      - WideEffect_Lockdown_post50
    scenario_colors: ["#7570B3", "#1B9E77", "#D95F02"]
    pdeath_labels: ["1% IFR"]
    display_dates: ["2020-05-01", "2020-07-01"]
